// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.domain;

import es.uca.iw.domain.Centro;
import es.uca.iw.domain.CentroDataOnDemand;
import es.uca.iw.domain.CentroIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CentroIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CentroIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CentroIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CentroIntegrationTest: @Transactional;
    
    @Autowired
    CentroDataOnDemand CentroIntegrationTest.dod;
    
    @Test
    public void CentroIntegrationTest.testCountCentroes() {
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", dod.getRandomCentro());
        long count = Centro.countCentroes();
        Assert.assertTrue("Counter for 'Centro' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CentroIntegrationTest.testFindCentro() {
        Centro obj = dod.getRandomCentro();
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Centro' failed to provide an identifier", id);
        obj = Centro.findCentro(id);
        Assert.assertNotNull("Find method for 'Centro' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Centro' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CentroIntegrationTest.testFindAllCentroes() {
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", dod.getRandomCentro());
        long count = Centro.countCentroes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Centro', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Centro> result = Centro.findAllCentroes();
        Assert.assertNotNull("Find all method for 'Centro' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Centro' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CentroIntegrationTest.testFindCentroEntries() {
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", dod.getRandomCentro());
        long count = Centro.countCentroes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Centro> result = Centro.findCentroEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Centro' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Centro' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CentroIntegrationTest.testFlush() {
        Centro obj = dod.getRandomCentro();
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Centro' failed to provide an identifier", id);
        obj = Centro.findCentro(id);
        Assert.assertNotNull("Find method for 'Centro' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCentro(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Centro' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CentroIntegrationTest.testMergeUpdate() {
        Centro obj = dod.getRandomCentro();
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Centro' failed to provide an identifier", id);
        obj = Centro.findCentro(id);
        boolean modified =  dod.modifyCentro(obj);
        Integer currentVersion = obj.getVersion();
        Centro merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Centro' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CentroIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", dod.getRandomCentro());
        Centro obj = dod.getNewTransientCentro(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Centro' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Centro' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Centro' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CentroIntegrationTest.testRemove() {
        Centro obj = dod.getRandomCentro();
        Assert.assertNotNull("Data on demand for 'Centro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Centro' failed to provide an identifier", id);
        obj = Centro.findCentro(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Centro' with identifier '" + id + "'", Centro.findCentro(id));
    }
    
}
