// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.domain;

import es.uca.iw.domain.Centro;
import es.uca.iw.domain.CentroDataOnDemand;
import es.uca.iw.domain.Formaciondemandante;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CentroDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CentroDataOnDemand: @Component;
    
    private Random CentroDataOnDemand.rnd = new SecureRandom();
    
    private List<Centro> CentroDataOnDemand.data;
    
    public Centro CentroDataOnDemand.getNewTransientCentro(int index) {
        Centro obj = new Centro();
        setIdFormacionDemandanteCentro(obj, index);
        setNombre(obj, index);
        return obj;
    }
    
    public void CentroDataOnDemand.setIdFormacionDemandanteCentro(Centro obj, int index) {
        Formaciondemandante idFormacionDemandanteCentro = null;
        obj.setIdFormacionDemandanteCentro(idFormacionDemandanteCentro);
    }
    
    public void CentroDataOnDemand.setNombre(Centro obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Centro CentroDataOnDemand.getSpecificCentro(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Centro obj = data.get(index);
        Long id = obj.getId();
        return Centro.findCentro(id);
    }
    
    public Centro CentroDataOnDemand.getRandomCentro() {
        init();
        Centro obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Centro.findCentro(id);
    }
    
    public boolean CentroDataOnDemand.modifyCentro(Centro obj) {
        return false;
    }
    
    public void CentroDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Centro.findCentroEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Centro' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Centro>();
        for (int i = 0; i < 10; i++) {
            Centro obj = getNewTransientCentro(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
