// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.domain;

import es.uca.iw.domain.CentroDataOnDemand;
import es.uca.iw.domain.DemandanteDataOnDemand;
import es.uca.iw.domain.FormacionDataOnDemand;
import es.uca.iw.domain.Formaciondemandante;
import es.uca.iw.domain.FormaciondemandanteDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FormaciondemandanteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FormaciondemandanteDataOnDemand: @Component;
    
    private Random FormaciondemandanteDataOnDemand.rnd = new SecureRandom();
    
    private List<Formaciondemandante> FormaciondemandanteDataOnDemand.data;
    
    @Autowired
    CentroDataOnDemand FormaciondemandanteDataOnDemand.centroDataOnDemand;
    
    @Autowired
    DemandanteDataOnDemand FormaciondemandanteDataOnDemand.demandanteDataOnDemand;
    
    @Autowired
    FormacionDataOnDemand FormaciondemandanteDataOnDemand.formacionDataOnDemand;
    
    public Formaciondemandante FormaciondemandanteDataOnDemand.getNewTransientFormaciondemandante(int index) {
        Formaciondemandante obj = new Formaciondemandante();
        return obj;
    }
    
    public Formaciondemandante FormaciondemandanteDataOnDemand.getSpecificFormaciondemandante(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Formaciondemandante obj = data.get(index);
        Long id = obj.getId();
        return Formaciondemandante.findFormaciondemandante(id);
    }
    
    public Formaciondemandante FormaciondemandanteDataOnDemand.getRandomFormaciondemandante() {
        init();
        Formaciondemandante obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Formaciondemandante.findFormaciondemandante(id);
    }
    
    public boolean FormaciondemandanteDataOnDemand.modifyFormaciondemandante(Formaciondemandante obj) {
        return false;
    }
    
    public void FormaciondemandanteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Formaciondemandante.findFormaciondemandanteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Formaciondemandante' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Formaciondemandante>();
        for (int i = 0; i < 10; i++) {
            Formaciondemandante obj = getNewTransientFormaciondemandante(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
