// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.domain;

import es.uca.iw.domain.TipoformacionIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoformacionIntegrationTest_Roo_Configurable {
    
    declare @type: TipoformacionIntegrationTest: @Configurable;
    
}
