// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.domain;

import es.uca.iw.domain.Tipoformacion;
import es.uca.iw.domain.TipoformacionDataOnDemand;
import es.uca.iw.domain.TipoformacionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoformacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipoformacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipoformacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipoformacionIntegrationTest: @Transactional;
    
    @Autowired
    TipoformacionDataOnDemand TipoformacionIntegrationTest.dod;
    
    @Test
    public void TipoformacionIntegrationTest.testCountTipoformacions() {
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", dod.getRandomTipoformacion());
        long count = Tipoformacion.countTipoformacions();
        Assert.assertTrue("Counter for 'Tipoformacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipoformacionIntegrationTest.testFindTipoformacion() {
        Tipoformacion obj = dod.getRandomTipoformacion();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to provide an identifier", id);
        obj = Tipoformacion.findTipoformacion(id);
        Assert.assertNotNull("Find method for 'Tipoformacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tipoformacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipoformacionIntegrationTest.testFindAllTipoformacions() {
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", dod.getRandomTipoformacion());
        long count = Tipoformacion.countTipoformacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tipoformacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tipoformacion> result = Tipoformacion.findAllTipoformacions();
        Assert.assertNotNull("Find all method for 'Tipoformacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tipoformacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipoformacionIntegrationTest.testFindTipoformacionEntries() {
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", dod.getRandomTipoformacion());
        long count = Tipoformacion.countTipoformacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tipoformacion> result = Tipoformacion.findTipoformacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tipoformacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tipoformacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipoformacionIntegrationTest.testFlush() {
        Tipoformacion obj = dod.getRandomTipoformacion();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to provide an identifier", id);
        obj = Tipoformacion.findTipoformacion(id);
        Assert.assertNotNull("Find method for 'Tipoformacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTipoformacion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tipoformacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoformacionIntegrationTest.testMergeUpdate() {
        Tipoformacion obj = dod.getRandomTipoformacion();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to provide an identifier", id);
        obj = Tipoformacion.findTipoformacion(id);
        boolean modified =  dod.modifyTipoformacion(obj);
        Integer currentVersion = obj.getVersion();
        Tipoformacion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tipoformacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoformacionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", dod.getRandomTipoformacion());
        Tipoformacion obj = dod.getNewTransientTipoformacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tipoformacion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Tipoformacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipoformacionIntegrationTest.testRemove() {
        Tipoformacion obj = dod.getRandomTipoformacion();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tipoformacion' failed to provide an identifier", id);
        obj = Tipoformacion.findTipoformacion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tipoformacion' with identifier '" + id + "'", Tipoformacion.findTipoformacion(id));
    }
    
}
